# 資料はこれ
# https://tt-computing.com/docker-nginx1_19-php7_4-mariadb10_5
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      # nginx Config
      - ./nginx/conf.d/50-my-config.conf:/etc/nginx/conf.d/50-my-config.conf
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      # nginx Logs
      - ./nginx/log:/var/log/nginx
      # source folder
      - .:/var/www
    environment:
      - MAX_FILESIZE=${MAX_FILESIZE}
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      # source folder
      - .:/var/www
      # php-fpm Config
      - ./php-fpm/conf.d/50-my-config.ini:/usr/local/etc/php/conf.d/50-my-config.ini
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_USER_PASSWORD}
      - TIMEZONE=${TIMEZONE}
      - MAX_FILESIZE=${MAX_FILESIZE}
      - PASS_PHRASE=${PASS_PHRASE}
      - CAPTCHA_DISABLE=${CAPTCHA_DISABLE}
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    volumes:
      # init SQL script
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Database Volume
      - db_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_USER_PASSWORD}

  php-myadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_USER_PASSWORD}
    depends_on:
      - mariadb

volumes:
  db_data:
